"""Gmail SMTP를 통해 분석 보고서를 HTML 이메일로 발송합니다."""
import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)

_SECTION_COLORS = {
    "핵심 요약": "#1a73e8",
    "SoC": "#0f9d58",
    "HBM": "#e37400",
    "SDV": "#a142f4",
    "휴머노이드": "#e52592",
    "공급망": "#1967d2",
    "경쟁": "#188038",
    "투자": "#c5221f",
    "규제": "#e37400",
    "전략": "#1a73e8",
}


def _section_color(title: str) -> str:
    for key, color in _SECTION_COLORS.items():
        if key in title:
            return color
    return "#5f6368"


def _markdown_to_html(text: str) -> str:
    """간단한 마크다운 → HTML 변환 (bullet, bold, 줄바꿈)."""
    import re

    lines = text.split("\n")
    html_lines = []
    in_list = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("- ") or stripped.startswith("• "):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", stripped[2:])
            html_lines.append(f"  <li>{content}</li>")
        else:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", stripped)
            if content:
                html_lines.append(f"<p>{content}</p>")

    if in_list:
        html_lines.append("</ul>")

    return "\n".join(html_lines)


def _build_daily_html(analysis: dict) -> str:
    date_str = analysis.get("date", "")
    article_count = analysis.get("article_count", 0)
    keywords = ", ".join(analysis.get("keywords_found", []))
    notion_url = analysis.get("notion_url", "")
    sections: dict = analysis.get("sections", {})

    sections_html = ""
    for title, content in sections.items():
        color = _section_color(title)
        body_html = _markdown_to_html(content)
        sections_html += f"""
        <div style="margin-bottom:28px; border-left:4px solid {color}; padding-left:16px;">
          <h2 style="color:{color}; font-size:15px; margin:0 0 10px 0; font-family:sans-serif;">{title}</h2>
          <div style="color:#3c4043; font-size:14px; line-height:1.7; font-family:sans-serif;">
            {body_html}
          </div>
        </div>
        """

    notion_btn = ""
    if notion_url:
        notion_btn = (
            f'<a href="{notion_url}" style="display:inline-block; margin-top:24px; '
            f'padding:10px 20px; background:#1a73e8; color:white; border-radius:4px; '
            f'text-decoration:none; font-family:sans-serif; font-size:13px;">'
            f"Notion에서 전체 보기</a>"
        )

    return f"""<!DOCTYPE html>
<html lang="ko">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="background:#f8f9fa; padding:0; margin:0;">
  <div style="max-width:700px; margin:0 auto; background:white; border-radius:8px; overflow:hidden;
              box-shadow:0 1px 3px rgba(0,0,0,0.12);">
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#1a73e8,#0f9d58); padding:32px 32px 24px;">
      <h1 style="color:white; margin:0; font-size:20px; font-family:sans-serif;">
        Automotive / AI Semiconductor Daily Brief
      </h1>
      <p style="color:rgba(255,255,255,0.85); margin:6px 0 0; font-size:13px; font-family:sans-serif;">
        {date_str} &nbsp;|&nbsp; 수집 기사 {article_count}건 &nbsp;|&nbsp; 키워드: {keywords}
      </p>
    </div>
    <!-- Body -->
    <div style="padding:32px;">
      {sections_html}
      {notion_btn}
    </div>
    <!-- Footer -->
    <div style="background:#f1f3f4; padding:16px 32px; text-align:center;
                color:#9aa0a6; font-size:11px; font-family:sans-serif;">
      Generated by Claude AI &nbsp;|&nbsp; Automotive/AI Semiconductor Strategy Analyzer
    </div>
  </div>
</body>
</html>"""


def _build_weekly_html(analysis: dict, week_label: str) -> str:
    sections: dict = analysis.get("sections", {})
    notion_url = analysis.get("notion_url", "")

    sections_html = ""
    for title, content in sections.items():
        color = _section_color(title)
        body_html = _markdown_to_html(content)
        sections_html += f"""
        <div style="margin-bottom:28px; border-left:4px solid {color}; padding-left:16px;">
          <h2 style="color:{color}; font-size:15px; margin:0 0 10px 0; font-family:sans-serif;">{title}</h2>
          <div style="color:#3c4043; font-size:14px; line-height:1.7; font-family:sans-serif;">
            {body_html}
          </div>
        </div>
        """

    notion_btn = ""
    if notion_url:
        notion_btn = (
            f'<a href="{notion_url}" style="display:inline-block; margin-top:24px; '
            f'padding:10px 20px; background:#a142f4; color:white; border-radius:4px; '
            f'text-decoration:none; font-family:sans-serif; font-size:13px;">'
            f"Notion에서 전체 보기</a>"
        )

    return f"""<!DOCTYPE html>
<html lang="ko">
<head><meta charset="UTF-8"></head>
<body style="background:#f8f9fa; padding:0; margin:0;">
  <div style="max-width:700px; margin:0 auto; background:white; border-radius:8px; overflow:hidden;
              box-shadow:0 1px 3px rgba(0,0,0,0.12);">
    <div style="background:linear-gradient(135deg,#a142f4,#1a73e8); padding:32px 32px 24px;">
      <h1 style="color:white; margin:0; font-size:20px; font-family:sans-serif;">
        Weekly Semiconductor Strategy Report
      </h1>
      <p style="color:rgba(255,255,255,0.85); margin:6px 0 0; font-size:13px; font-family:sans-serif;">
        {week_label} &nbsp;|&nbsp; 일별 분석 {analysis.get('daily_count', 0)}개 취합
      </p>
    </div>
    <div style="padding:32px;">
      {sections_html}
      {notion_btn}
    </div>
    <div style="background:#f1f3f4; padding:16px 32px; text-align:center;
                color:#9aa0a6; font-size:11px; font-family:sans-serif;">
      Generated by Claude AI &nbsp;|&nbsp; Automotive/AI Semiconductor Strategy Analyzer
    </div>
  </div>
</body>
</html>"""


def send_daily_email(analysis: dict) -> None:
    """Daily 분석 보고서를 Gmail로 발송."""
    date_str = analysis.get("date", "")
    subject = f"[Daily Brief] {date_str} Automotive/AI Semiconductor 동향"
    html_body = _build_daily_html(analysis)
    _send(subject, html_body)


def send_weekly_email(analysis: dict, week_label: str) -> None:
    """Weekly 보고서를 Gmail로 발송."""
    subject = f"[Weekly] {week_label} Semiconductor Strategy Report"
    html_body = _build_weekly_html(analysis, week_label)
    _send(subject, html_body)


def _send(subject: str, html_body: str) -> None:
    gmail_addr = os.environ["GMAIL_ADDRESS"]
    app_password = os.environ["GMAIL_APP_PASSWORD"]
    recipients_raw = os.environ.get("RECIPIENT_EMAILS", gmail_addr)
    recipients = [r.strip() for r in recipients_raw.split(",") if r.strip()]

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"Semiconductor Brief <{gmail_addr}>"
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(gmail_addr, app_password)
        server.sendmail(gmail_addr, recipients, msg.as_string())

    logger.info("이메일 발송 완료: %s → %s", subject[:50], recipients)
