"""Gmail SMTP를 통해 분석 보고서를 HTML 이메일로 발송합니다 (PPT 첨부 포함)."""
import logging
import os
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

logger = logging.getLogger(__name__)

_SECTION_COLORS = {
    "핵심 요약":          "#00B4D8",
    "기술적 의미":        "#0096C7",
    "AI Agent":           "#0077B6",
    "비즈니스 영향":      "#48CAE4",
    "Ecosystem":          "#ADE8F4",
    "향후 전망":          "#90E0EF",
    "메모리":             "#023E8A",
    "스토리지 Workload":  "#0077B6",
    "지역별":             "#00B4D8",
    "Why Now":            "#48CAE4",
}


def _color(title: str) -> str:
    for k, v in _SECTION_COLORS.items():
        if k in title:
            return v
    return "#0096C7"


def _md_to_html(text: str) -> str:
    import re
    lines, html, in_ul = text.split("\n"), [], False
    for line in lines:
        s = line.strip()
        if s.startswith("- ") or s.startswith("• "):
            if not in_ul:
                html.append("<ul style='margin:4px 0; padding-left:18px;'>")
                in_ul = True
            c = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s[2:])
            c = re.sub(r"\[(.+?)\]\((https?://[^\)]+)\)", r'<a href="\2" style="color:#00B4D8">\1</a>', c)
            html.append(f"<li style='margin:3px 0'>{c}</li>")
        else:
            if in_ul:
                html.append("</ul>")
                in_ul = False
            c = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
            c = re.sub(r"\[(.+?)\]\((https?://[^\)]+)\)", r'<a href="\2" style="color:#00B4D8">\1</a>', c)
            if c:
                html.append(f"<p style='margin:5px 0'>{c}</p>")
    if in_ul:
        html.append("</ul>")
    return "\n".join(html)


def _build_html(analysis: dict, report_type: str = "Daily") -> str:
    date_str   = analysis.get("date", "")
    art_count  = analysis.get("article_count", 0)
    keywords   = ", ".join(analysis.get("keywords_found", []))
    provider   = analysis.get("provider", "-")
    notion_url = analysis.get("notion_url", "")
    sections   = analysis.get("sections", {})
    week_label = analysis.get("week_label", "")

    subtitle = week_label if report_type == "Weekly" else date_str
    header_gradient = (
        "linear-gradient(135deg,#a142f4,#0077B6)"
        if report_type == "Weekly"
        else "linear-gradient(135deg,#023E8A,#00B4D8)"
    )

    sections_html = ""
    for title, content in sections.items():
        col = _color(title)
        sections_html += f"""
        <div style="margin-bottom:24px;border-left:4px solid {col};padding-left:14px;">
          <h2 style="color:{col};font-size:14px;margin:0 0 8px;font-family:sans-serif;">{title}</h2>
          <div style="color:#CAE9FF;font-size:13px;line-height:1.75;font-family:sans-serif;">
            {_md_to_html(content)}
          </div>
        </div>"""

    notion_btn = (
        f'<a href="{notion_url}" style="display:inline-block;margin-top:20px;'
        f'padding:9px 18px;background:#00B4D8;color:#0D1B2A;border-radius:4px;'
        f'text-decoration:none;font-family:sans-serif;font-size:13px;font-weight:bold;">'
        f"Notion에서 전체 보기</a>"
    ) if notion_url else ""

    return f"""<!DOCTYPE html>
<html lang="ko"><head><meta charset="UTF-8"></head>
<body style="background:#0D1B2A;padding:0;margin:0;">
  <div style="max-width:720px;margin:0 auto;background:#162133;border-radius:8px;overflow:hidden;">
    <div style="background:{header_gradient};padding:28px 28px 20px;">
      <h1 style="color:#fff;margin:0;font-size:18px;font-family:sans-serif;">
        [{report_type}] Automotive / AI Semiconductor Brief
      </h1>
      <p style="color:rgba(255,255,255,.8);margin:6px 0 0;font-size:12px;font-family:sans-serif;">
        {subtitle} &nbsp;|&nbsp; 기사 {art_count}건 &nbsp;|&nbsp; 키워드: {keywords}
      </p>
      <p style="color:rgba(255,255,255,.65);margin:3px 0 0;font-size:11px;font-family:sans-serif;">
        🤖 AI 기여: {analysis.get("model_attribution", provider)}
      </p>
      {'<p style="color:rgba(255,255,255,.6);margin:3px 0 0;font-size:11px;font-family:sans-serif;">※ PPT 보고서가 첨부되어 있습니다.</p>' if report_type == "Daily" else ""}
    </div>
    <div style="padding:28px;">{sections_html}{notion_btn}</div>
    <div style="background:#0D1B2A;padding:14px 28px;text-align:center;
                color:#445566;font-size:10px;font-family:sans-serif;">
      Generated by Multi-LLM Strategy Analyzer (Claude / Gemini / GPT)
    </div>
  </div>
</body></html>"""


def _send(subject: str, html_body: str, attachments: list[str] | None = None) -> None:
    gmail_addr  = os.environ["GMAIL_ADDRESS"]
    app_pw      = os.environ["GMAIL_APP_PASSWORD"]
    recipients  = [r.strip() for r in os.environ.get("RECIPIENT_EMAILS", gmail_addr).split(",") if r.strip()]

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"]    = f"Semiconductor Brief <{gmail_addr}>"
    msg["To"]      = ", ".join(recipients)

    alt = MIMEMultipart("alternative")
    alt.attach(MIMEText(html_body, "html", "utf-8"))
    msg.attach(alt)

    for path in (attachments or []):
        p = Path(path)
        if not p.exists():
            logger.warning("첨부 파일 없음: %s", path)
            continue
        with open(p, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", f'attachment; filename="{p.name}"')
        msg.attach(part)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as srv:
        srv.login(gmail_addr, app_pw)
        srv.sendmail(gmail_addr, recipients, msg.as_string())

    logger.info("이메일 발송 완료: %s → %s (첨부: %d개)", subject[:50], recipients, len(attachments or []))


def send_daily_email(
    analysis: dict,
    ppt_path: str | None = None,
    extra_attachments: list[str] | None = None,
) -> None:
    date_str    = analysis.get("date", "")
    attribution = analysis.get("model_attribution", analysis.get("provider", "-"))
    subject     = f"[Daily Brief] {date_str} Automotive/AI Semiconductor 동향 [{attribution[:30]}]"
    html        = _build_html(analysis, "Daily")

    # 첨부 파일: PPT + Markdown(NotebookLM용) + 기타
    attachments: list[str] = []
    if ppt_path:
        attachments.append(ppt_path)
    for p in (extra_attachments or []):
        if p and p not in attachments:
            attachments.append(p)

    _send(subject, html, attachments=attachments)


def send_weekly_email(
    analysis: dict,
    week_label: str,
    ppt_path: str | None = None,
    extra_attachments: list[str] | None = None,
) -> None:
    analysis["week_label"] = week_label
    subject = f"[Weekly] {week_label} Semiconductor Strategy Report"
    html    = _build_html(analysis, "Weekly")

    attachments: list[str] = []
    if ppt_path:
        attachments.append(ppt_path)
    for p in (extra_attachments or []):
        if p and p not in attachments:
            attachments.append(p)

    _send(subject, html, attachments=attachments)
